### ISSUE TITLE
Strange issue with vKey witness problem

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#133]
```
HW-CLI 1.11.0-rc3
Cardano-App 5.0.0
Carcano-Cli 1.35.3
Chain: PreProd
Era: Alonzo
```

Asset Minting transaction + 2x metadata files attached, the following example works:

Transaction creation:
```json
{
    "type": "Unwitnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a60081825820164ae288559ea58ff805750589bbd0816ffda3e9084e01322d3385daaf5ca1b60001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf821a00680dbba1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e09021a0002e195031a005d0a3909a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e010758206f06a72a7e5e681582a35158205d77394390e939a0dfaffc8c826c71a1c9cb4ba101818200581c45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678df5d90103a100a301a164746573746c7365636f6e6420656e74727902a164746573746b666972737420656e7472791902a2a1636d736781782c6d696e74696e672077697468206e6f6e2d63616e6f6e6963616c206d65746164617461206174746163686564"
}
```

After it went thru HW-CLI canonical order correction:
```json
{
    "type": "Unwitnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a60081825820164ae288559ea58ff805750589bbd0816ffda3e9084e01322d3385daaf5ca1b60001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf821a00680dbba1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e09021a0002e195031a005d0a390758206f06a72a7e5e681582a35158205d77394390e939a0dfaffc8c826c71a1c9cb4b09a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e01a101818200581c45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678df5d90103a100a301a164746573746c7365636f6e6420656e74727902a164746573746b666972737420656e7472791902a2a1636d736781782c6d696e74696e672077697468206e6f6e2d63616e6f6e6963616c206d65746164617461206174746163686564"
}
```

After the signing via HW-Wallet:
```json
{
    "type": "Witnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a60081825820164ae288559ea58ff805750589bbd0816ffda3e9084e01322d3385daaf5ca1b60001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf821a00680dbba1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e09021a0002e195031a005d0a390758206f06a72a7e5e681582a35158205d77394390e939a0dfaffc8c826c71a1c9cb4b09a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e01a200828258201287e9ce9e00a603d250b557146aa0581fc4edf277a244ce39d3b2f2ced5072f584024fa74d077fa2ca2346c2be000e8d74cc52df6e9b2bcc7f9f87443d3d07ee3a3082bceab9e6a102af6758e631c68f7821a461b46359fddb08a6529877017b50d8258200186abff41121414f856fd8cf613399f9a30e413bb1c75c2413f46121f02034958409af92fb74d7556d07e7ec5aba2d80ff7516aa6fdb2d5384de524b665e70b7891788cb2521d0047abea658f311cb85b6fdcd9fee02a10d8e64bc9123d0a7d870b01818200581c45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678df5d90103a100a301a164746573746c7365636f6e6420656e74727902a164746573746b666972737420656e7472791902a2a1636d736781782c6d696e74696e672077697468206e6f6e2d63616e6f6e6963616c206d65746164617461206174746163686564"
}
```

-> SUBMIT -> OK

```console
$ cardano-cli transaction view ... <above signed txfile>
```
```yaml
auxiliary scripts: null
certificates: null
collateral inputs: []
era: Alonzo
fee: 188821 Lovelace
inputs:
- 164ae288559ea58ff805750589bbd0816ffda3e9084e01322d3385daaf5ca1b6#0
metadata:
  '1':
  - - test
    - second entry
  '2':
  - - test
    - first entry
  '674':
  - - msg
    - - minting with non-canonical metadata attached
mint:
  policy 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518:
    asset 4154414441636f696e (ATADAcoin): 1
outputs:
- address: addr_test1qp6fwmz547h5gnmu6jvmmpge4tr9j2cnkg4e6kqh7rd9c5sr6gz4xgyf45hhs95f9ch0g2zfk76j0z8yrvlagwnwq88sq0cm9e
  address era: Shelley
  amount:
    lovelace: 6819259
    policy 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518:
      asset 4154414441636f696e (ATADAcoin): 9
  datum: null
  network: Testnet
  payment credential key hash: 74976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c52
  reference script: null
  stake reference:
    stake credential key hash: 03d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf
required signers (payment key hashes needed for scripts): null
update proposal: null
validity range:
  lower bound: null
  upper bound: 6097465
withdrawals: null
witnesses:
- key: VKey (VerKeyEd25519DSIGN "1287e9ce9e00a603d250b557146aa0581fc4edf277a244ce39d3b2f2ced5072f")
  signature: SignedDSIGN (SigEd25519DSIGN "24fa74d077fa2ca2346c2be000e8d74cc52df6e9b2bcc7f9f87443d3d07ee3a3082bceab9e6a102af6758e631c68f7821a461b46359fddb08a6529877017b50d")
- key: VKey (VerKeyEd25519DSIGN "0186abff41121414f856fd8cf613399f9a30e413bb1c75c2413f46121f020349")
  signature: SignedDSIGN (SigEd25519DSIGN "9af92fb74d7556d07e7ec5aba2d80ff7516aa6fdb2d5384de524b665e70b7891788cb2521d0047abea658f311cb85b6fdcd9fee02a10d8e64bc9123d0a7d870b")
```

------------
This is the same transaction again with the only difference that the order of the 2x metadata files have switched places during the cardano-cli build-raw command:

Transaction creation:
```json
{
    "type": "Unwitnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a60081825820c6afe424d3dd9a96bc08c33436b82df647c97fa77f051c800bb0c7a586982fcc0001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf821a00652c26a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e0a021a0002e195031a005d0af209a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e010758206f06a72a7e5e681582a35158205d77394390e939a0dfaffc8c826c71a1c9cb4ba101818200581c45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678df5d90103a100a301a164746573746c7365636f6e6420656e74727902a164746573746b666972737420656e7472791902a2a1636d736781782c6d696e74696e672077697468206e6f6e2d63616e6f6e6963616c206d65746164617461206174746163686564"
}
```

After it went thru HW-CLI canonical order correction:
```json
{
    "type": "Unwitnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a60081825820c6afe424d3dd9a96bc08c33436b82df647c97fa77f051c800bb0c7a586982fcc0001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf821a00652c26a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e0a021a0002e195031a005d0af20758206f06a72a7e5e681582a35158205d77394390e939a0dfaffc8c826c71a1c9cb4b09a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e01a101818200581c45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678df5d90103a100a301a164746573746c7365636f6e6420656e74727902a164746573746b666972737420656e7472791902a2a1636d736781782c6d696e74696e672077697468206e6f6e2d63616e6f6e6963616c206d65746164617461206174746163686564"
}
```

After the signing via HW-Wallet:
```json
{
    "type": "Witnessed Tx AlonzoEra",
    "description": "Ledger Cddl Format",
    "cborHex": "84a60081825820c6afe424d3dd9a96bc08c33436b82df647c97fa77f051c800bb0c7a586982fcc0001818258390074976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c5203d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf821a00652c26a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e0a021a0002e195031a005d0af20758206f06a72a7e5e681582a35158205d77394390e939a0dfaffc8c826c71a1c9cb4b09a1581c34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518a1494154414441636f696e01a200828258201287e9ce9e00a603d250b557146aa0581fc4edf277a244ce39d3b2f2ced5072f5840eb5d7bb96974d6a777da2d15ddd27ad76901ddffff28034b533951d5591fb85eab131dc5f1a453f742d4fbec94b4fa65abc5b036d67ca4b35ba7e4204e17e90e8258200186abff41121414f856fd8cf613399f9a30e413bb1c75c2413f46121f0203495840be5197f4fb7807afa972c39ccb32f2b600df2995fdefd7de17d52297fae863df26e4946a5d252f1aff074b301253e262f74efddfaf15b1547138496aa1c8b40701818200581c45d70e54f3b5e9c5a2b0cd417028197bd6f5fa5378c2f5eba896678df5d90103a100a301a164746573746c7365636f6e6420656e74727902a164746573746b666972737420656e7472791902a2a1636d736781782c6d696e74696e672077697468206e6f6e2d63616e6f6e6963616c206d65746164617461206174746163686564"
}
```

-> SUBMIT -> **ERROR**
```console
Submitting the transaction via the node... Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN "1287e9ce9e00a603d250b557146aa0581fc4edf277a244ce39d3b2f2ced5072f")]))])
```

Transaction View shows the following:
```console
$ cardano-cli transaction view ... <above signed txfile>
```
```yaml
${cardanocli} transaction view --tx-file /tmp/ledger-red.payment.tx
auxiliary scripts: null
certificates: null
collateral inputs: []
era: Alonzo
fee: 188821 Lovelace
inputs:
- c6afe424d3dd9a96bc08c33436b82df647c97fa77f051c800bb0c7a586982fcc#0
metadata:
  '1':
  - - test
    - second entry
  '2':
  - - test
    - first entry
  '674':
  - - msg
    - - minting with non-canonical metadata attached
mint:
  policy 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518:
    asset 4154414441636f696e (ATADAcoin): 1
outputs:
- address: addr_test1qp6fwmz547h5gnmu6jvmmpge4tr9j2cnkg4e6kqh7rd9c5sr6gz4xgyf45hhs95f9ch0g2zfk76j0z8yrvlagwnwq88sq0cm9e
  address era: Shelley
  amount:
    lovelace: 6630438
    policy 34250edd1e9836f5378702fbf9416b709bc140e04f668cc355208518:
      asset 4154414441636f696e (ATADAcoin): 10
  datum: null
  network: Testnet
  payment credential key hash: 74976c54afaf444f7cd499bd8519aac6592b13b22b9d5817f0da5c52
  reference script: null
  stake reference:
    stake credential key hash: 03d205532089ad2f7816892e2ef42849b7b52788e41b3fd43a6e01cf
required signers (payment key hashes needed for scripts): null
update proposal: null
validity range:
  lower bound: null
  upper bound: 6097650
withdrawals: null
witnesses:
- key: VKey (VerKeyEd25519DSIGN "1287e9ce9e00a603d250b557146aa0581fc4edf277a244ce39d3b2f2ced5072f")
  signature: SignedDSIGN (SigEd25519DSIGN "eb5d7bb96974d6a777da2d15ddd27ad76901ddffff28034b533951d5591fb85eab131dc5f1a453f742d4fbec94b4fa65abc5b036d67ca4b35ba7e4204e17e90e")
- key: VKey (VerKeyEd25519DSIGN "0186abff41121414f856fd8cf613399f9a30e413bb1c75c2413f46121f020349")
  signature: SignedDSIGN (SigEd25519DSIGN "be5197f4fb7807afa972c39ccb32f2b600df2995fdefd7de17d52297fae863df26e4946a5d252f1aff074b301253e262f74efddfaf15b1547138496aa1c8b407")
```
